package com.storepilot.backend.common.security

import com.storepilot.backend.notification.NotificationProperties
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import jakarta.servlet.http.HttpServletResponse
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.springframework.security.oauth2.jwt.JwtDecoder
import software.amazon.awssdk.services.cognitoidentityprovider.CognitoIdentityProviderClient

class AuthControllerTest {
    private val cognitoClient = mockk<CognitoIdentityProviderClient>()
    private val cognitoProperties = CognitoProperties(
        userPoolId = "pool-123",
        oauthDomain = "storepilot-dev.auth.ap-southeast-2.amazoncognito.com",
        oauthClientId = "oauth-client-id",
        oauthRedirectUri = "https://example.test/api/auth/google/callback",
    )
    private val currentActor = mockk<CurrentActor>()
    private val notificationProperties = NotificationProperties()
    private val jwtDecoder = mockk<JwtDecoder>()
    private val emailVerificationService = mockk<EmailVerificationService>()
    private val controller = AuthController(
        cognitoClient, cognitoProperties, currentActor, notificationProperties, jwtDecoder, emailVerificationService,
    )

    // --- resolveGoogleSignInOutcome: the pure (existingRole x intent) decision table ---

    @Test
    fun `groupless plus buyer intent assigns buyer and lands on account`() {
        val outcome = resolveGoogleSignInOutcome(intent = "buyer", existingRole = null)
        assertEquals("buyer", outcome.groupToAssign)
        assertEquals("/account", outcome.redirectPath)
        assertFalse(outcome.rejected)
    }

    @Test
    fun `groupless plus seller intent assigns no group and lands on onboarding`() {
        val outcome = resolveGoogleSignInOutcome(intent = "seller", existingRole = null)
        assertNull(outcome.groupToAssign)
        assertEquals("/onboarding", outcome.redirectPath)
        assertFalse(outcome.rejected)
    }

    @Test
    fun `existing buyer plus buyer intent is a normal returning sign-in`() {
        val outcome = resolveGoogleSignInOutcome(intent = "buyer", existingRole = "buyer")
        assertNull(outcome.groupToAssign)
        assertEquals("/account", outcome.redirectPath)
        assertFalse(outcome.rejected)
    }

    @Test
    fun `existing seller plus seller intent is a normal returning sign-in`() {
        val outcome = resolveGoogleSignInOutcome(intent = "seller", existingRole = "seller")
        assertNull(outcome.groupToAssign)
        assertEquals("/dashboard", outcome.redirectPath)
        assertFalse(outcome.rejected)
    }

    @Test
    fun `existing buyer plus seller intent is rejected back to seller login`() {
        val outcome = resolveGoogleSignInOutcome(intent = "seller", existingRole = "buyer")
        assertTrue(outcome.rejected)
        assertEquals("/login?error=google_wrong_account_type&existingRole=buyer", outcome.redirectPath)
    }

    @Test
    fun `existing seller plus buyer intent is rejected back to buyer login`() {
        val outcome = resolveGoogleSignInOutcome(intent = "buyer", existingRole = "seller")
        assertTrue(outcome.rejected)
        assertEquals("/account/login?error=google_wrong_account_type&existingRole=seller", outcome.redirectPath)
    }

    @Test
    fun `an admin identity is rejected regardless of intent`() {
        assertTrue(resolveGoogleSignInOutcome(intent = "buyer", existingRole = "admin").rejected)
        assertTrue(resolveGoogleSignInOutcome(intent = "seller", existingRole = "admin").rejected)
    }

    @Test
    fun `loginPathFor picks the seller vs buyer login page`() {
        assertEquals("/login", loginPathFor("seller"))
        assertEquals("/account/login", loginPathFor("buyer"))
    }

    // --- resolveAppRole: filters out Cognito's auto-generated per-IdP group ---

    @Test
    fun `resolveAppRole ignores the autogenerated per-identity-provider group`() {
        // Reproduces the real bug: Cognito adds every Google-authenticated user to
        // "{userPoolId}_Google" alongside their real app role — a naive
        // groups.firstOrNull() can pick that instead of the real role depending on
        // list order.
        assertEquals("buyer", resolveAppRole(listOf("ap-southeast-2_NmGrljWsz_Google", "buyer")))
        assertEquals("buyer", resolveAppRole(listOf("buyer", "ap-southeast-2_NmGrljWsz_Google")))
        assertEquals("seller", resolveAppRole(listOf("ap-southeast-2_NmGrljWsz_Google", "seller")))
    }

    @Test
    fun `resolveAppRole returns null for a groupless identity even with the autogenerated group present`() {
        assertNull(resolveAppRole(listOf("ap-southeast-2_NmGrljWsz_Google")))
        assertNull(resolveAppRole(emptyList()))
    }

    @Test
    fun `resolveAppRole recognizes admin`() {
        assertEquals("admin", resolveAppRole(listOf("admin")))
    }

    // --- googleStart(): URL construction + validation ---

    @Test
    fun `googleStart defaults to buyer intent and carries it as state`() {
        val response = mockk<HttpServletResponse>(relaxed = true)
        val urlSlot = slot<String>()
        every { response.sendRedirect(capture(urlSlot)) } returns Unit

        controller.googleStart(intent = "buyer", response = response, platform = "web")

        assertTrue(urlSlot.captured.startsWith("https://storepilot-dev.auth.ap-southeast-2.amazoncognito.com/oauth2/authorize"))
        assertTrue(urlSlot.captured.contains("&identity_provider=Google"))
        assertTrue(urlSlot.captured.contains("&state=buyer"))
    }

    @Test
    fun `googleStart with seller intent carries seller as state`() {
        val response = mockk<HttpServletResponse>(relaxed = true)
        val urlSlot = slot<String>()
        every { response.sendRedirect(capture(urlSlot)) } returns Unit

        controller.googleStart(intent = "seller", response = response, platform = "web")

        assertTrue(urlSlot.captured.contains("&state=seller"))
    }

    @Test
    fun `googleStart rejects an invalid intent`() {
        val response = mockk<HttpServletResponse>(relaxed = true)
        assertThrows(IllegalArgumentException::class.java) {
            controller.googleStart(intent = "admin", response = response, platform = "web")
        }
    }
}
